"""initial

Revision ID: fd7d099fb4af
Revises:
Create Date: 2026-05-16 22:15:17.605668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7d099fb4af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('post', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('is_default_pass', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_login', ['login'], unique=False)
        batch_op.create_index('idx_users_role', ['role_id'], unique=False)
        batch_op.create_index('idx_users_visible', ['is_hidden'], unique=False, postgresql_where=sa.text('is_hidden = FALSE'))

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('link_yougile', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_archived', ['is_archived'], unique=False)
        batch_op.create_index('idx_tasks_archived_at', ['archived_at'], unique=False, postgresql_where=sa.text('is_archived = TRUE'))
        batch_op.create_index('idx_tasks_author', ['author_id'], unique=False)
        batch_op.create_index('idx_tasks_dept', ['department_id'], unique=False)
        batch_op.create_index('idx_tasks_received', ['received_at'], unique=False)

    op.create_table('favorites',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('datetime_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index('idx_units_active', ['user_id'], unique=False, postgresql_where=sa.text('datetime_end IS NULL'))
        batch_op.create_index('idx_units_task', ['task_id'], unique=False)
        batch_op.create_index('idx_units_user', ['user_id'], unique=False)

    # Seed: 4 фиксированные роли
    op.execute(
        "INSERT INTO roles (name, level) VALUES "
        "('Сотрудник', 1), ('Менеджер', 2), ('Администратор', 3), ('Суперадминистратор', 4) "
        "ON CONFLICT (name) DO NOTHING"
    )
    # Seed: первый пользователь admin/admin с ролью Суперадминистратор (id=4)
    # is_default_pass=FALSE — смена пароля при первом входе не требуется
    op.execute(
        "INSERT INTO users (fio, login, hash_password, role_id, is_default_pass, is_hidden, created_at) "
        "VALUES ('Администратор', 'admin', crypt('admin', gen_salt('bf')), 4, FALSE, FALSE, NOW()) "
        "ON CONFLICT (login) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('idx_units_user')
        batch_op.drop_index('idx_units_task')
        batch_op.drop_index('idx_units_active', postgresql_where=sa.text('datetime_end IS NULL'))

    op.drop_table('units')
    op.drop_table('favorites')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_received')
        batch_op.drop_index('idx_tasks_dept')
        batch_op.drop_index('idx_tasks_author')
        batch_op.drop_index('idx_tasks_archived_at', postgresql_where=sa.text('is_archived = TRUE'))
        batch_op.drop_index('idx_tasks_archived')

    op.drop_table('tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_visible', postgresql_where=sa.text('is_hidden = FALSE'))
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_login')

    op.drop_table('users')
    op.drop_table('unit_types')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
