# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/ai.v1.AiService/Status',
                request_serializer=ai__pb2.StatusRequest.SerializeToString,
                response_deserializer=ai__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ai.v1.AiService/Chat',
                request_serializer=ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/ai.v1.AiService/Embed',
                request_serializer=ai__pb2.EmbedRequest.SerializeToString,
                response_deserializer=ai__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/ai.v1.AiService/SemanticSearch',
                request_serializer=ai__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=ai__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.ReindexTask = channel.unary_unary(
                '/ai.v1.AiService/ReindexTask',
                request_serializer=ai__pb2.ReindexTaskRequest.SerializeToString,
                response_deserializer=ai__pb2.ReindexTaskResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Включён ли ИИ у компании и какие модели настроены.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Один ход chat completion. messages_json/tools_json — сырые JSON
        в формате OpenAI API (массивы), tool_calls_json — сырой ответ модели.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Эмбеддинг произвольного текста моделью компании.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Семантический поиск задач компании по task_embeddings (pgvector).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReindexTask(self, request, context):
        """Переиндексировать задачу (фоном внутри aisvc); зовётся после изменений задачи.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=ai__pb2.StatusRequest.FromString,
                    response_serializer=ai__pb2.StatusResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ai__pb2.ChatRequest.FromString,
                    response_serializer=ai__pb2.ChatResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=ai__pb2.EmbedRequest.FromString,
                    response_serializer=ai__pb2.EmbedResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=ai__pb2.SemanticSearchRequest.FromString,
                    response_serializer=ai__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'ReindexTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReindexTask,
                    request_deserializer=ai__pb2.ReindexTaskRequest.FromString,
                    response_serializer=ai__pb2.ReindexTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/Status',
            ai__pb2.StatusRequest.SerializeToString,
            ai__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/Chat',
            ai__pb2.ChatRequest.SerializeToString,
            ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/Embed',
            ai__pb2.EmbedRequest.SerializeToString,
            ai__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/SemanticSearch',
            ai__pb2.SemanticSearchRequest.SerializeToString,
            ai__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReindexTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AiService/ReindexTask',
            ai__pb2.ReindexTaskRequest.SerializeToString,
            ai__pb2.ReindexTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
