# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import calls_pb2 as calls__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calls_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCall = channel.unary_unary(
                '/calls.v1.CallService/StartCall',
                request_serializer=calls__pb2.StartCallRequest.SerializeToString,
                response_deserializer=calls__pb2.StartCallResponse.FromString,
                _registered_method=True)
        self.InviteToCall = channel.unary_unary(
                '/calls.v1.CallService/InviteToCall',
                request_serializer=calls__pb2.InviteToCallRequest.SerializeToString,
                response_deserializer=calls__pb2.InviteToCallResponse.FromString,
                _registered_method=True)
        self.AcceptCall = channel.unary_unary(
                '/calls.v1.CallService/AcceptCall',
                request_serializer=calls__pb2.AcceptCallRequest.SerializeToString,
                response_deserializer=calls__pb2.AcceptCallResponse.FromString,
                _registered_method=True)
        self.DeclineCall = channel.unary_unary(
                '/calls.v1.CallService/DeclineCall',
                request_serializer=calls__pb2.DeclineCallRequest.SerializeToString,
                response_deserializer=calls__pb2.DeclineCallResponse.FromString,
                _registered_method=True)
        self.LeaveCall = channel.unary_unary(
                '/calls.v1.CallService/LeaveCall',
                request_serializer=calls__pb2.LeaveCallRequest.SerializeToString,
                response_deserializer=calls__pb2.LeaveCallResponse.FromString,
                _registered_method=True)
        self.EndCall = channel.unary_unary(
                '/calls.v1.CallService/EndCall',
                request_serializer=calls__pb2.EndCallRequest.SerializeToString,
                response_deserializer=calls__pb2.EndCallResponse.FromString,
                _registered_method=True)


class CallServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteToCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclineCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCall,
                    request_deserializer=calls__pb2.StartCallRequest.FromString,
                    response_serializer=calls__pb2.StartCallResponse.SerializeToString,
            ),
            'InviteToCall': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteToCall,
                    request_deserializer=calls__pb2.InviteToCallRequest.FromString,
                    response_serializer=calls__pb2.InviteToCallResponse.SerializeToString,
            ),
            'AcceptCall': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptCall,
                    request_deserializer=calls__pb2.AcceptCallRequest.FromString,
                    response_serializer=calls__pb2.AcceptCallResponse.SerializeToString,
            ),
            'DeclineCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclineCall,
                    request_deserializer=calls__pb2.DeclineCallRequest.FromString,
                    response_serializer=calls__pb2.DeclineCallResponse.SerializeToString,
            ),
            'LeaveCall': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveCall,
                    request_deserializer=calls__pb2.LeaveCallRequest.FromString,
                    response_serializer=calls__pb2.LeaveCallResponse.SerializeToString,
            ),
            'EndCall': grpc.unary_unary_rpc_method_handler(
                    servicer.EndCall,
                    request_deserializer=calls__pb2.EndCallRequest.FromString,
                    response_serializer=calls__pb2.EndCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calls.v1.CallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calls.v1.CallService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/StartCall',
            calls__pb2.StartCallRequest.SerializeToString,
            calls__pb2.StartCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteToCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/InviteToCall',
            calls__pb2.InviteToCallRequest.SerializeToString,
            calls__pb2.InviteToCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/AcceptCall',
            calls__pb2.AcceptCallRequest.SerializeToString,
            calls__pb2.AcceptCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclineCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/DeclineCall',
            calls__pb2.DeclineCallRequest.SerializeToString,
            calls__pb2.DeclineCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/LeaveCall',
            calls__pb2.LeaveCallRequest.SerializeToString,
            calls__pb2.LeaveCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calls.v1.CallService/EndCall',
            calls__pb2.EndCallRequest.SerializeToString,
            calls__pb2.EndCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
