# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groove.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'groove.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroove.proto\x12\tgroove.v1\";\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bhttp_status\x18\x03 \x01(\x05\"/\n\x0cHookResponse\x12\x1f\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x10.groove.v1.Error\"\x81\x01\n\x12UnitStartedRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0f\n\x07unit_id\x18\x03 \x01(\x03\x12\x11\n\tunit_name\x18\x04 \x01(\t\x12\x0f\n\x07task_id\x18\x05 \x01(\x03\x12\x11\n\ttask_name\x18\x06 \x01(\t\"\x92\x01\n\x12UnitStoppedRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0f\n\x07unit_id\x18\x03 \x01(\x03\x12\x11\n\tunit_name\x18\x04 \x01(\t\x12\x0f\n\x07task_id\x18\x05 \x01(\x03\x12\x11\n\ttask_name\x18\x06 \x01(\t\x12\x0f\n\x07minutes\x18\x07 \x01(\x05\"a\n\x11TaskClosedRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x14\n\x0chero_user_id\x18\x02 \x01(\x03\x12\x0f\n\x07task_id\x18\x03 \x01(\x03\x12\x11\n\ttask_name\x18\x04 \x01(\t\",\n\x11PetMessageRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\x03\x32\xaf\x02\n\rGrooveService\x12G\n\rOnUnitStarted\x12\x1d.groove.v1.UnitStartedRequest\x1a\x17.groove.v1.HookResponse\x12G\n\rOnUnitStopped\x12\x1d.groove.v1.UnitStoppedRequest\x1a\x17.groove.v1.HookResponse\x12\x45\n\x0cOnTaskClosed\x12\x1c.groove.v1.TaskClosedRequest\x1a\x17.groove.v1.HookResponse\x12\x45\n\x0cOnPetMessage\x12\x1c.groove.v1.PetMessageRequest\x1a\x17.groove.v1.HookResponseB=Z;github.com/DmitriyODS/gw2/back-go/pkg/gen/groovepb;groovepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groove_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/DmitriyODS/gw2/back-go/pkg/gen/groovepb;groovepb'
  _globals['_ERROR']._serialized_start=27
  _globals['_ERROR']._serialized_end=86
  _globals['_HOOKRESPONSE']._serialized_start=88
  _globals['_HOOKRESPONSE']._serialized_end=135
  _globals['_UNITSTARTEDREQUEST']._serialized_start=138
  _globals['_UNITSTARTEDREQUEST']._serialized_end=267
  _globals['_UNITSTOPPEDREQUEST']._serialized_start=270
  _globals['_UNITSTOPPEDREQUEST']._serialized_end=416
  _globals['_TASKCLOSEDREQUEST']._serialized_start=418
  _globals['_TASKCLOSEDREQUEST']._serialized_end=515
  _globals['_PETMESSAGEREQUEST']._serialized_start=517
  _globals['_PETMESSAGEREQUEST']._serialized_end=561
  _globals['_GROOVESERVICE']._serialized_start=564
  _globals['_GROOVESERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
