# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import groove_pb2 as groove__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in groove_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrooveServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnUnitStarted = channel.unary_unary(
                '/groove.v1.GrooveService/OnUnitStarted',
                request_serializer=groove__pb2.UnitStartedRequest.SerializeToString,
                response_deserializer=groove__pb2.HookResponse.FromString,
                _registered_method=True)
        self.OnUnitStopped = channel.unary_unary(
                '/groove.v1.GrooveService/OnUnitStopped',
                request_serializer=groove__pb2.UnitStoppedRequest.SerializeToString,
                response_deserializer=groove__pb2.HookResponse.FromString,
                _registered_method=True)
        self.OnTaskClosed = channel.unary_unary(
                '/groove.v1.GrooveService/OnTaskClosed',
                request_serializer=groove__pb2.TaskClosedRequest.SerializeToString,
                response_deserializer=groove__pb2.HookResponse.FromString,
                _registered_method=True)
        self.OnPetMessage = channel.unary_unary(
                '/groove.v1.GrooveService/OnPetMessage',
                request_serializer=groove__pb2.PetMessageRequest.SerializeToString,
                response_deserializer=groove__pb2.HookResponse.FromString,
                _registered_method=True)


class GrooveServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def OnUnitStarted(self, request, context):
        """Сотрудник начал юнит (Flask, после коммита unit_service).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnUnitStopped(self, request, context):
        """Сотрудник завершил юнит: событие ленты + грувы + лечение + квесты.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnTaskClosed(self, request, context):
        """Задача закрыта: событие ленты + грувы героя + прогресс рейда.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPetMessage(self, request, context):
        """Хозяин написал в pet-чат (msgsvc): Грувик отвечает асинхронно.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrooveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnUnitStarted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUnitStarted,
                    request_deserializer=groove__pb2.UnitStartedRequest.FromString,
                    response_serializer=groove__pb2.HookResponse.SerializeToString,
            ),
            'OnUnitStopped': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUnitStopped,
                    request_deserializer=groove__pb2.UnitStoppedRequest.FromString,
                    response_serializer=groove__pb2.HookResponse.SerializeToString,
            ),
            'OnTaskClosed': grpc.unary_unary_rpc_method_handler(
                    servicer.OnTaskClosed,
                    request_deserializer=groove__pb2.TaskClosedRequest.FromString,
                    response_serializer=groove__pb2.HookResponse.SerializeToString,
            ),
            'OnPetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPetMessage,
                    request_deserializer=groove__pb2.PetMessageRequest.FromString,
                    response_serializer=groove__pb2.HookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groove.v1.GrooveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groove.v1.GrooveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrooveService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnUnitStarted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groove.v1.GrooveService/OnUnitStarted',
            groove__pb2.UnitStartedRequest.SerializeToString,
            groove__pb2.HookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnUnitStopped(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groove.v1.GrooveService/OnUnitStopped',
            groove__pb2.UnitStoppedRequest.SerializeToString,
            groove__pb2.HookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnTaskClosed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groove.v1.GrooveService/OnTaskClosed',
            groove__pb2.TaskClosedRequest.SerializeToString,
            groove__pb2.HookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groove.v1.GrooveService/OnPetMessage',
            groove__pb2.PetMessageRequest.SerializeToString,
            groove__pb2.HookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
