# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import messenger_pb2 as messenger__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in messenger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessengerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsureDialog = channel.unary_unary(
                '/messenger.v1.MessengerService/EnsureDialog',
                request_serializer=messenger__pb2.EnsureDialogRequest.SerializeToString,
                response_deserializer=messenger__pb2.EnsureDialogResponse.FromString,
                _registered_method=True)
        self.CreateCallMessage = channel.unary_unary(
                '/messenger.v1.MessengerService/CreateCallMessage',
                request_serializer=messenger__pb2.CreateCallMessageRequest.SerializeToString,
                response_deserializer=messenger__pb2.CreateCallMessageResponse.FromString,
                _registered_method=True)
        self.GetCallMessage = channel.unary_unary(
                '/messenger.v1.MessengerService/GetCallMessage',
                request_serializer=messenger__pb2.GetCallMessageRequest.SerializeToString,
                response_deserializer=messenger__pb2.GetCallMessageResponse.FromString,
                _registered_method=True)
        self.PostBotMessage = channel.unary_unary(
                '/messenger.v1.MessengerService/PostBotMessage',
                request_serializer=messenger__pb2.PostBotMessageRequest.SerializeToString,
                response_deserializer=messenger__pb2.PostBotMessageResponse.FromString,
                _registered_method=True)
        self.ListRecentMessages = channel.unary_unary(
                '/messenger.v1.MessengerService/ListRecentMessages',
                request_serializer=messenger__pb2.ListRecentMessagesRequest.SerializeToString,
                response_deserializer=messenger__pb2.ListRecentMessagesResponse.FromString,
                _registered_method=True)


class MessengerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnsureDialog(self, request, context):
        """Парный диалог (создаётся ДО StartCall, если его ещё нет).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCallMessage(self, request, context):
        """Системная плашка звонка kind='call' в парном диалоге.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallMessage(self, request, context):
        """Актуальный снапшот плашки звонка — для message:updated при смене статуса.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostBotMessage(self, request, context):
        """Бот-сообщение Грувика (sender NULL + is_bot) в pet-чат; msgsvc сам публикует message:new.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecentMessages(self, request, context):
        """Последние сообщения диалога — контекст для AI-ответа pet-чата.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsureDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureDialog,
                    request_deserializer=messenger__pb2.EnsureDialogRequest.FromString,
                    response_serializer=messenger__pb2.EnsureDialogResponse.SerializeToString,
            ),
            'CreateCallMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCallMessage,
                    request_deserializer=messenger__pb2.CreateCallMessageRequest.FromString,
                    response_serializer=messenger__pb2.CreateCallMessageResponse.SerializeToString,
            ),
            'GetCallMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallMessage,
                    request_deserializer=messenger__pb2.GetCallMessageRequest.FromString,
                    response_serializer=messenger__pb2.GetCallMessageResponse.SerializeToString,
            ),
            'PostBotMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PostBotMessage,
                    request_deserializer=messenger__pb2.PostBotMessageRequest.FromString,
                    response_serializer=messenger__pb2.PostBotMessageResponse.SerializeToString,
            ),
            'ListRecentMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecentMessages,
                    request_deserializer=messenger__pb2.ListRecentMessagesRequest.FromString,
                    response_serializer=messenger__pb2.ListRecentMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.v1.MessengerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.v1.MessengerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessengerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnsureDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.v1.MessengerService/EnsureDialog',
            messenger__pb2.EnsureDialogRequest.SerializeToString,
            messenger__pb2.EnsureDialogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCallMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.v1.MessengerService/CreateCallMessage',
            messenger__pb2.CreateCallMessageRequest.SerializeToString,
            messenger__pb2.CreateCallMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.v1.MessengerService/GetCallMessage',
            messenger__pb2.GetCallMessageRequest.SerializeToString,
            messenger__pb2.GetCallMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostBotMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.v1.MessengerService/PostBotMessage',
            messenger__pb2.PostBotMessageRequest.SerializeToString,
            messenger__pb2.PostBotMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecentMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.v1.MessengerService/ListRecentMessages',
            messenger__pb2.ListRecentMessagesRequest.SerializeToString,
            messenger__pb2.ListRecentMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
